### ISSUE TITLE
SBML Import

### ISSUE THREAD

**Issue by VitaminBrad** [CiaranWelsh/pycotools3#9]
Hi!

I'm curious why pycotools3 is not recognizing my SBML file as an SBMl file?
![image](https://user-images.githubusercontent.com/5053928/83944314-ea264900-a802-11ea-8e0b-f4675bca50dc.png)

![image](https://user-images.githubusercontent.com/5053928/83944318-f7433800-a802-11ea-9823-73c7c573e56b.png)

![image](https://user-images.githubusercontent.com/5053928/83944325-088c4480-a803-11ea-850e-2406ee742787.png)

Any idea?

Thank you!

Best regards,
Brad

**Comment by VitaminBrad** [comment]
I made a bit of progress, haha:
![image](https://user-images.githubusercontent.com/5053928/83944587-db409600-a804-11ea-9fa7-b04432e7720b.png)

**Comment by VitaminBrad** [comment]
I'm sorry to ask so many questions, but how would one go about doing that? (configuring environment variables so that copasiSE command gives the CopasiSE help text.

Thanks!

**Comment by VitaminBrad** [comment]
I found out I was able to reproduce this error by only changing one thing. 
The only difference between Doyle_Tau.sbml (the one it works on) and Doyle_Tau_changed.sbml (the only that only the COPASI UI can import and work on) is the following added reaction:
![image](https://user-images.githubusercontent.com/5053928/83945138-e0074900-a808-11ea-8070-14464c7c6f33.png)


All other differences are trivial (since these are just the result of passing it through libSBML):
![image](https://user-images.githubusercontent.com/5053928/83945132-d251c380-a808-11ea-9e04-81d53fb83826.png)

Any idea why this might trigger the above error?

Thanks!

best regards,
Brad

**Comment by VitaminBrad** [comment]
The code that causes it:
![image](https://user-images.githubusercontent.com/5053928/83945187-52782900-a809-11ea-9881-7a22aae1babf.png)

And here is evidence it works within pycotools once COPASI has converted it:

![image](https://user-images.githubusercontent.com/5053928/83945201-66bc2600-a809-11ea-9e4e-57b9a549a840.png)

p.s.
perhaps also worth noting?:
![image](https://user-images.githubusercontent.com/5053928/83945209-78053280-a809-11ea-8be7-7a3b5db62a21.png)


Thanks again!!

**Comment by CiaranWelsh** [comment]
Hi Brad, 

The first post might just be a naming problem. Pycotools3 checks for a `*.sbml` extension, so just renaming `*.xml` to `*.sbml` might work. 

The problem in the second post is usually issued when Pycotools3 cannot access CopasiSE via the command line. Does the command `CopasiSE` or `CopasiUI` work from the command line / powershell / terminal ? If not then you should add the path to the copasi `bin` directory to the system `PATH` environment variable. However, it sounds like this is not your issue as you've said it you've had it working under some conditions.  

...To be honest, without taking an indepth look at what you are doing, I cannot say for sure what the issue is. One potential way forward for you could be to do what Pycotools3 does behind the scenes for importing SBML files into copasi. Basically, it use copasi simulation engine (CopasiSE), aka command line copasi. 

In Python 
```
>>> import os
>>> f = "/path/to/sbml.sbml"
>>> copasi_exe = "/path/to/copasi/executable"
>>> os.system(f"CopasiSE -i {f}") # the same as running this command in terminal. 
```
The `-i` flag means import (see the CopasiSE help message for more details).  Then, once you have the CopasiML it seems to work. You could also just import using the copasi UI or run `CopasiSE -i /path/to/sbml` from cmd/powershell/terminal. The key is to use copasi to build a copasiML from the sbml before using pycotools. 

The last thing I think I should mention is that I believe Pycotools3 was developed on Copasi version 4.25 or 4.26. For the most part Pycotools3 tends to work with newer versions of COPASI, but sometimes there are small changes that break pycotools. One way to find out how operational pycotools3 is with newer Copasi releases would be to run the tests. If you wanted to do this you could clone the [pycotools repository](https://github.com/CiaranWelsh/pycotools3), open in pycharm, right click the tests folder and hit run all tests. 

Hopefully some of this has helped, 

Ciaran

**Comment by matthiaskoenig** [comment]
@VitaminBrad I would first check if your SBML file is valid (i.e. does not contain any errors) via the SBML validator http://www.sbml.org/validator/.
Furthermore, I would check if you can import the SBML via the COPASI-GUI interface.
Then I would check that the file really exists, i.e. do a 
```
assert os.path.isfile(sbml_file)
```
There could be a small typo or missing directory in your path, so check that the file really exists.

Best M

**Comment by VitaminBrad** [comment]
Thank you very much both for the feedback. It was very helpful.

Alternatively, is there a way to check if something is a valid SBML file within libSBML? Even a API call, at the very least, seems more appropriate here. 

I feel like I'm trying to convert a PDF into a word document with a free webtool everytime I upload my SBML to the website. 😆 

Thanks again!

Brad

**Comment by VitaminBrad** [comment]
The libSBML document object does have validateSBML method.

Thanks again for all the help! I will close the issue now. 

Once again: much appreciated. I, of course, will be citing pycotools in my publication, please offer any other citations you think would be appropriate including as well.

Thank you.

**Comment by CiaranWelsh** [comment]
No problem. 

I would cite copasi definately (no pycotools without copasi) and tellurium if you've used the model construction via antimony features.

All the best, 

Ciaran
